$("#register-1").append("<a href='首页.html'><img src='img/menu/左箭头.svg'/></a> <p>登录</p>")
$("#register-2").append("<img src='img/logo/睿乐logo.svg'/>")
$("#register-3").append("<input type='text' placeholder='手机/邮箱/用户名' />")
$("#register-4").append("<input type='password' placeholder='请输入密码' /> <button>忘记密码</button>")
$("#register-5").append("<p>短信验证码登录</p> <p><a href='注册.html'>手机快速注册</a></p>")
$("#register-5 p:first").addClass("margin-left")
$("#register-5 p:last").addClass("margin-left2")
$("#register-6").append("<div><span>登录</span></div>")
$("#register-7").append("<div>登录即表示你已同意睿乐隐私政策</div>")